// https://www.annuityexpertadvice.com/states-that-dont-tax-retirement-income

const DATA = [
  {
    id: 'ss',
    name: 'Social Security',
    states: [
      {name: 'CO'},
      {name: 'CA'},
      {name: 'CT', note: '50%'},
      {name: 'FL'},
      {name: 'KS'},
      {name: 'MN', note: '33%'},
      {name: 'MO', note: 'prorated'},
      {name: 'MT'},
      {name: 'NJ'},
      {name: 'RI', note: 'prorated'},
      {name: 'VT'},
      {name: 'WV'},
    ],
  },
  {
    id: 'pension',
    name: 'Pension',
    states: [
      {name: 'AK'},
      {name: 'AL'},
      {name: 'FL'},
      {name: 'HI'},
      {name: 'IL'},
      {name: 'MS'},
      {name: 'NH'},
      {name: 'NV'},
      {name: 'PA'},
      {name: 'SD'},
      {name: 'TN'},
      {name: 'TX'},
      {name: 'WA'},
      {name: 'WY'},
    ],
  },
  {
    id: 'tsp',
    name: 'TSP',
    states: [
      {name: 'AK'},
      {name: 'FL'},
      {name: 'IL'},
      {name: 'NV'},
      {name: 'NH'},
      {name: 'MS'},
      {name: 'PA'},
      {name: 'SD'},
      {name: 'TN'},
      {name: 'TX'},
      {name: 'WA'},
      {name: 'WY'},
    ],
  },
  {
    id: 'income',
    name: 'Income Tax',
    states: [
      {name: 'AK'},
      {name: 'FL'},
      {name: 'NV'},
      {name: 'NH'},
      {name: 'SD'},
      {name: 'TN'},
      {name: 'TX'},
      {name: 'WA'},
      {name: 'WY'},
    ],
  },
  {
    id: 'sales',
    name: 'Sales Tax',
    states: [
      {name: 'AK'},
      {name: 'DE'},
      {name: 'MT'},
      {name: 'NH'},
      {name: 'OR'},
    ],
  },
  {
    id: 'inheritance',
    name: 'Inheritance',
    states: [
      {name: 'AK'},
      {name: 'AL'},
      {name: 'AR'},
      {name: 'AZ'},
      {name: 'CA'},
      {name: 'CO'},
      {name: 'DE'},
      {name: 'FL'},
      {name: 'GA'},
      {name: 'IA'},
      {name: 'ID'},
      {name: 'IN'},
      {name: 'KS'},
      {name: 'KY', note: 'Estate Tax Only'},
      {name: 'LA', note: 'Inheritance Tax only'},
      {
        name: 'MD',
        note: 'Taxes can be an exemption if requirements are met',
      },
      {name: 'MI'},
      {name: 'MO'},
      {name: 'MS'},
      {name: 'MT'},
      {name: 'NC'},
      {name: 'ND'},
      {name: 'NE', note: 'Estate Tax Only'},
      {name: 'NH'},
      {name: 'NJ', note: 'Estate Tax Only'},
      {name: 'NM'},
      {name: 'NV'},
      {name: 'OH'},
      {name: 'OK'},
      {
        name: 'PA',
        note: 'No Estate Tax. No Inheritance Tax Depending On Beneficiary',
      },
      {name: 'SC'},
      {name: 'SD'},
      {name: 'TN'},
      {name: 'TX'},
      {name: 'UT'},
      {name: 'VA'},
      {name: 'WV'},
      {name: 'WI'},
      {name: 'WY'},
    ],
  },
];

export default DATA;
